/* action types */
export const CHANGE_PAGEROUTE = 'CHANGE_PAGEROUTE';
export const SET_INITIALROUTE = 'SET_INITIALROUTE';

export const SEARCH_USERNAME = 'SEARCH_USERNAME';
export const UPDATE_USERNAME_INPUT = 'UPDATE_USERNAME_INPUT';
export const REQUEST_USERNAME = 'REQUEST_ USERNAME';
export const FETCH_USERNAME = 'FETCH_USERNAME_';
export const FETCH_USERNAME_SUCCESS = 'FETCH_USERNAME_SUCCESS';
export const FETCH_USERNAME_NOT_FOUND = 'FETCH_USERNAME_NOT_FOUND';
export const FETCH_USERNAME_FAILURE = 'FETCH_USERNAME_FAILURE';
export const RECEIVE_USERNAME = 'RECEIVE_USERNAME';
export const ADD_USERNAMETOLIST = 'ADD_USERNAMETOLIST';
export const REMOVE_USERNAMEFROMLIST = 'REMOVE_USERNAMEFROMLIST';

export const FETCH_GAMESINCOMMON = 'FETCH_GAMESINCOMMON';
export const REQUEST_USER_GAMELISTS = 'REQUEST_USER_GAMELISTS';
export const REMOVE_USER_GAMELISTS = 'REQUEST_USER_GAMELISTS';
export const RECEIVED_USER_GAMELIST = 'RECEIVE_USER_GAMELIST';
export const RECEIVED_TOTAL_USER_GAMELISTS = 'RECEIVED_TOTAL_USER_GAMELISTS';